backend:
  name: git-gateway
  branch: main
publish_mode: simple

media_folder: "images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Images"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    files:
      - label: "Gallery Images"
        name: "gallery_images"
        file: "gallery/gallery.md"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }