backend:
  name: github
  repo: naseel1/hard_rock
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "images/gallery"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text", required: false }