backend:
  name: git-gateway
  branch: main

media_folder: "images/gallery"
public_folder: "/images/gallery"

collections:
  - name: "gallery"
    label: "Gallery Images"
    folder: "images/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Images", name: "images", widget: "list", field: { label: "Image", name: "image", widget: "image" } }